name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Install dependencies
        run: |
          git lfs pull
          uv pip install setuptools
          uv sync --extra dev --no-build-isolation-package infomap
      - name: Test with pytest
        run: |
          uv run pytest
